In [1]:
#Import dependencies
import pandas as pd
import os
import numpy as np

In [2]:
#Load CSV
file_to_load = ("SF 2019 CO.csv")
CO_2019 =pd.read_csv(file_to_load)
CO_2019.head()

Date Source   Site ID  POC  Daily Max 8-hour CO Concentration UNITS  \
0  01/01/2019    AQS  60010009    1                                0.4   ppm   
1  01/02/2019    AQS  60010009    1                                0.6   ppm   
2  01/03/2019    AQS  60010009    1                                0.6   ppm   
3  01/04/2019    AQS  60010009    1                                0.7   ppm   
4  01/05/2019    AQS  60010009    1                                0.6   ppm   

   DAILY_AQI_VALUE Site Name  DAILY_OBS_COUNT  PERCENT_COMPLETE  \
0                5   Oakland               18              75.0   
1                7   Oakland               24             100.0   
2                7   Oakland               24             100.0   
3                8   Oakland               24             100.0   
4                7   Oakland               24             100.0   

   AQS_PARAMETER_CODE AQS_PARAMETER_DESC  CBSA_CODE  \
0               42101    Carbon monoxide      41860   
1               42101    Carbon monoxide      41860   
2               42101    Carbon monoxide      41860   
3               42101    Carbon monoxide      41860   
4               42101    Carbon monoxide      41860   

                           CBSA_NAME  STATE_CODE       STATE  COUNTY_CODE  \
0  San Francisco-Oakland-Hayward, CA           6  California            1   
1  San Francisco-Oakland-Hayward, CA           6  California            1   
2  San Francisco-Oakland-Hayward, CA           6  California            1   
3  San Francisco-Oakland-Hayward, CA           6  California            1   
4  San Francisco-Oakland-Hayward, CA           6  California            1   

    COUNTY  SITE_LATITUDE  SITE_LONGITUDE  
0  Alameda      37.743065     -122.169935  
1  Alameda      37.743065     -122.169935  
2  Alameda      37.743065     -122.169935  
3  Alameda      37.743065     -122.169935  
4  Alameda      37.743065     -122.169935

In [3]:
#Check Columns
CO_2019.columns

Index(['Date', 'Source', 'Site ID', 'POC', 'Daily Max 8-hour CO Concentration',
       'UNITS', 'DAILY_AQI_VALUE', 'Site Name', 'DAILY_OBS_COUNT',
       'PERCENT_COMPLETE', 'AQS_PARAMETER_CODE', 'AQS_PARAMETER_DESC',
       'CBSA_CODE', 'CBSA_NAME', 'STATE_CODE', 'STATE', 'COUNTY_CODE',
       'COUNTY', 'SITE_LATITUDE', 'SITE_LONGITUDE'],
      dtype='object')

In [4]:
#Check Null Values
CO_2019.columns.isnull()

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False])

In [5]:
#Drop Columns
CO_2019 = CO_2019.drop(columns=['Source','Site ID','POC','Site Name','AQS_PARAMETER_CODE','AQS_PARAMETER_DESC', 'CBSA_CODE','STATE_CODE','STATE','COUNTY_CODE'], axis=1)

In [6]:
#Check DataFrame
CO_2019.head()

Date  Daily Max 8-hour CO Concentration UNITS  DAILY_AQI_VALUE  \
0  01/01/2019                                0.4   ppm                5   
1  01/02/2019                                0.6   ppm                7   
2  01/03/2019                                0.6   ppm                7   
3  01/04/2019                                0.7   ppm                8   
4  01/05/2019                                0.6   ppm                7   

   DAILY_OBS_COUNT  PERCENT_COMPLETE                          CBSA_NAME  \
0               18              75.0  San Francisco-Oakland-Hayward, CA   
1               24             100.0  San Francisco-Oakland-Hayward, CA   
2               24             100.0  San Francisco-Oakland-Hayward, CA   
3               24             100.0  San Francisco-Oakland-Hayward, CA   
4               24             100.0  San Francisco-Oakland-Hayward, CA   

    COUNTY  SITE_LATITUDE  SITE_LONGITUDE  
0  Alameda      37.743065     -122.169935  
1  Alameda      37.743065     -122.169935  
2  Alameda      37.743065     -122.169935  
3  Alameda      37.743065     -122.169935  
4  Alameda      37.743065     -122.169935

In [7]:
#Check Count
CO_2019.count()

Date                                 3984
Daily Max 8-hour CO Concentration    3984
UNITS                                3984
DAILY_AQI_VALUE                      3984
DAILY_OBS_COUNT                      3984
PERCENT_COMPLETE                     3984
CBSA_NAME                            3984
COUNTY                               3984
SITE_LATITUDE                        3984
SITE_LONGITUDE                       3984
dtype: int64

In [9]:
##Load CSV for NO2
file_to_load = ("SF 2019 NO2.csv")
NO2_2019 =pd.read_csv(file_to_load)
NO2_2019.head()

Date Source   Site ID  POC  Daily Max 1-hour NO2 Concentration UNITS  \
0  01/01/2019    AQS  60010007    1                                25.8   ppb   
1  01/02/2019    AQS  60010007    1                                34.7   ppb   
2  01/03/2019    AQS  60010007    1                                31.7   ppb   
3  01/04/2019    AQS  60010007    1                                37.2   ppb   
4  01/05/2019    AQS  60010007    1                                26.8   ppb   

   DAILY_AQI_VALUE  Site Name  DAILY_OBS_COUNT  PERCENT_COMPLETE  \
0               24  Livermore               23              96.0   
1               32  Livermore               23              96.0   
2               29  Livermore               23              96.0   
3               35  Livermore               23              96.0   
4               25  Livermore               23              96.0   

   AQS_PARAMETER_CODE      AQS_PARAMETER_DESC  CBSA_CODE  \
0               42602  Nitrogen dioxide (NO2)      41860   
1               42602  Nitrogen dioxide (NO2)      41860   
2               42602  Nitrogen dioxide (NO2)      41860   
3               42602  Nitrogen dioxide (NO2)      41860   
4               42602  Nitrogen dioxide (NO2)      41860   

                           CBSA_NAME  STATE_CODE       STATE  COUNTY_CODE  \
0  San Francisco-Oakland-Hayward, CA           6  California            1   
1  San Francisco-Oakland-Hayward, CA           6  California            1   
2  San Francisco-Oakland-Hayward, CA           6  California            1   
3  San Francisco-Oakland-Hayward, CA           6  California            1   
4  San Francisco-Oakland-Hayward, CA           6  California            1   

    COUNTY  SITE_LATITUDE  SITE_LONGITUDE  
0  Alameda      37.687526     -121.784217  
1  Alameda      37.687526     -121.784217  
2  Alameda      37.687526     -121.784217  
3  Alameda      37.687526     -121.784217  
4  Alameda      37.687526     -121.784217

In [10]:
#Check Columns
NO2_2019.columns

Index(['Date', 'Source', 'Site ID', 'POC',
       'Daily Max 1-hour NO2 Concentration', 'UNITS', 'DAILY_AQI_VALUE',
       'Site Name', 'DAILY_OBS_COUNT', 'PERCENT_COMPLETE',
       'AQS_PARAMETER_CODE', 'AQS_PARAMETER_DESC', 'CBSA_CODE', 'CBSA_NAME',
       'STATE_CODE', 'STATE', 'COUNTY_CODE', 'COUNTY', 'SITE_LATITUDE',
       'SITE_LONGITUDE'],
      dtype='object')

In [11]:
#Check Null Values
NO2_2019.columns.isnull()

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False])

In [12]:
#Drop Columns
NO2_2019 = NO2_2019.drop(columns=['Source','Site ID','POC','Site Name','AQS_PARAMETER_CODE','AQS_PARAMETER_DESC', 'CBSA_CODE','STATE_CODE','STATE','COUNTY_CODE'], axis=1)

In [13]:
#Check DataFrame
NO2_2019.head()

Date  Daily Max 1-hour NO2 Concentration UNITS  DAILY_AQI_VALUE  \
0  01/01/2019                                25.8   ppb               24   
1  01/02/2019                                34.7   ppb               32   
2  01/03/2019                                31.7   ppb               29   
3  01/04/2019                                37.2   ppb               35   
4  01/05/2019                                26.8   ppb               25   

   DAILY_OBS_COUNT  PERCENT_COMPLETE                          CBSA_NAME  \
0               23              96.0  San Francisco-Oakland-Hayward, CA   
1               23              96.0  San Francisco-Oakland-Hayward, CA   
2               23              96.0  San Francisco-Oakland-Hayward, CA   
3               23              96.0  San Francisco-Oakland-Hayward, CA   
4               23              96.0  San Francisco-Oakland-Hayward, CA   

    COUNTY  SITE_LATITUDE  SITE_LONGITUDE  
0  Alameda      37.687526     -121.784217  
1  Alameda      37.687526     -121.784217  
2  Alameda      37.687526     -121.784217  
3  Alameda      37.687526     -121.784217  
4  Alameda      37.687526     -121.784217

In [14]:
#Check Count
NO2_2019.count()

Date                                  4640
Daily Max 1-hour NO2 Concentration    4640
UNITS                                 4640
DAILY_AQI_VALUE                       4640
DAILY_OBS_COUNT                       4640
PERCENT_COMPLETE                      4640
CBSA_NAME                             4640
COUNTY                                4640
SITE_LATITUDE                         4640
SITE_LONGITUDE                        4640
dtype: int64

In [15]:
##Load CSV for Ozone
file_to_load = ("SF 2019 Ozone.csv")
Ozone_2019 =pd.read_csv(file_to_load)
Ozone_2019.head()

Date Source   Site ID  POC  Daily Max 8-hour Ozone Concentration  \
0  01/01/2019    AQS  60010007    1                                 0.032   
1  01/02/2019    AQS  60010007    1                                 0.021   
2  01/03/2019    AQS  60010007    1                                 0.026   
3  01/04/2019    AQS  60010007    1                                 0.021   
4  01/05/2019    AQS  60010007    1                                 0.036   

  UNITS  DAILY_AQI_VALUE  Site Name  DAILY_OBS_COUNT  PERCENT_COMPLETE  \
0   ppm               30  Livermore               17             100.0   
1   ppm               19  Livermore               17             100.0   
2   ppm               24  Livermore               17             100.0   
3   ppm               19  Livermore               17             100.0   
4   ppm               33  Livermore               17             100.0   

   AQS_PARAMETER_CODE AQS_PARAMETER_DESC  CBSA_CODE  \
0               44201              Ozone      41860   
1               44201              Ozone      41860   
2               44201              Ozone      41860   
3               44201              Ozone      41860   
4               44201              Ozone      41860   

                           CBSA_NAME  STATE_CODE       STATE  COUNTY_CODE  \
0  San Francisco-Oakland-Hayward, CA           6  California            1   
1  San Francisco-Oakland-Hayward, CA           6  California            1   
2  San Francisco-Oakland-Hayward, CA           6  California            1   
3  San Francisco-Oakland-Hayward, CA           6  California            1   
4  San Francisco-Oakland-Hayward, CA           6  California            1   

    COUNTY  SITE_LATITUDE  SITE_LONGITUDE  
0  Alameda      37.687526     -121.784217  
1  Alameda      37.687526     -121.784217  
2  Alameda      37.687526     -121.784217  
3  Alameda      37.687526     -121.784217  
4  Alameda      37.687526     -121.784217

In [16]:
#Check Columns
Ozone_2019.columns

Index(['Date', 'Source', 'Site ID', 'POC',
       'Daily Max 8-hour Ozone Concentration', 'UNITS', 'DAILY_AQI_VALUE',
       'Site Name', 'DAILY_OBS_COUNT', 'PERCENT_COMPLETE',
       'AQS_PARAMETER_CODE', 'AQS_PARAMETER_DESC', 'CBSA_CODE', 'CBSA_NAME',
       'STATE_CODE', 'STATE', 'COUNTY_CODE', 'COUNTY', 'SITE_LATITUDE',
       'SITE_LONGITUDE'],
      dtype='object')

In [17]:
#Check Null Values
Ozone_2019.columns.isnull()

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False])

In [18]:
#Drop Columns
Ozone_2019 = Ozone_2019.drop(columns=['Source','Site ID','POC','Site Name','AQS_PARAMETER_CODE','AQS_PARAMETER_DESC', 'CBSA_CODE','STATE_CODE','STATE','COUNTY_CODE'], axis=1)

In [19]:
#Check DataFrame
Ozone_2019.head()

Date  Daily Max 8-hour Ozone Concentration UNITS  DAILY_AQI_VALUE  \
0  01/01/2019                                 0.032   ppm               30   
1  01/02/2019                                 0.021   ppm               19   
2  01/03/2019                                 0.026   ppm               24   
3  01/04/2019                                 0.021   ppm               19   
4  01/05/2019                                 0.036   ppm               33   

   DAILY_OBS_COUNT  PERCENT_COMPLETE                          CBSA_NAME  \
0               17             100.0  San Francisco-Oakland-Hayward, CA   
1               17             100.0  San Francisco-Oakland-Hayward, CA   
2               17             100.0  San Francisco-Oakland-Hayward, CA   
3               17             100.0  San Francisco-Oakland-Hayward, CA   
4               17             100.0  San Francisco-Oakland-Hayward, CA   

    COUNTY  SITE_LATITUDE  SITE_LONGITUDE  
0  Alameda      37.687526     -121.784217  
1  Alameda      37.687526     -121.784217  
2  Alameda      37.687526     -121.784217  
3  Alameda      37.687526     -121.784217  
4  Alameda      37.687526     -121.784217

In [20]:
#Check count
Ozone_2019.count()

Date                                    4273
Daily Max 8-hour Ozone Concentration    4273
UNITS                                   4273
DAILY_AQI_VALUE                         4273
DAILY_OBS_COUNT                         4273
PERCENT_COMPLETE                        4273
CBSA_NAME                               4273
COUNTY                                  4273
SITE_LATITUDE                           4273
SITE_LONGITUDE                          4273
dtype: int64

In [21]:
##Load CSV for Pb
file_to_load = ("SF 2019 Pb.csv")
Pb_2019 =pd.read_csv(file_to_load)
Pb_2019.head()

Date Source   Site ID  POC  Daily Mean Pb Concentration     UNITS  \
0  01/09/2019    AQS  60750005    7                      0.00148  ug/m3 SC   
1  01/21/2019    AQS  60750005    7                      0.00387  ug/m3 SC   
2  02/02/2019    AQS  60750005    7                      0.00065  ug/m3 SC   
3  02/14/2019    AQS  60750005    7                      0.00065  ug/m3 SC   
4  02/26/2019    AQS  60750005    7                      0.00065  ug/m3 SC   

  DAILY_AQI_VALUE      Site Name  DAILY_OBS_COUNT  PERCENT_COMPLETE  \
0               .  San Francisco                1             100.0   
1               .  San Francisco                1             100.0   
2               .  San Francisco                1             100.0   
3               .  San Francisco                1             100.0   
4               .  San Francisco                1             100.0   

   AQS_PARAMETER_CODE AQS_PARAMETER_DESC  CBSA_CODE  \
0               12128     Lead (TSP) STP      41860   
1               12128     Lead (TSP) STP      41860   
2               12128     Lead (TSP) STP      41860   
3               12128     Lead (TSP) STP      41860   
4               12128     Lead (TSP) STP      41860   

                           CBSA_NAME  STATE_CODE       STATE  COUNTY_CODE  \
0  San Francisco-Oakland-Hayward, CA           6  California           75   
1  San Francisco-Oakland-Hayward, CA           6  California           75   
2  San Francisco-Oakland-Hayward, CA           6  California           75   
3  San Francisco-Oakland-Hayward, CA           6  California           75   
4  San Francisco-Oakland-Hayward, CA           6  California           75   

          COUNTY  SITE_LATITUDE  SITE_LONGITUDE  
0  San Francisco      37.765946     -122.399044  
1  San Francisco      37.765946     -122.399044  
2  San Francisco      37.765946     -122.399044  
3  San Francisco      37.765946     -122.399044  
4  San Francisco      37.765946     -122.399044

In [22]:
#Check Columns
Pb_2019.columns

Index(['Date', 'Source', 'Site ID', 'POC', 'Daily Mean Pb Concentration',
       'UNITS', 'DAILY_AQI_VALUE', 'Site Name', 'DAILY_OBS_COUNT',
       'PERCENT_COMPLETE', 'AQS_PARAMETER_CODE', 'AQS_PARAMETER_DESC',
       'CBSA_CODE', 'CBSA_NAME', 'STATE_CODE', 'STATE', 'COUNTY_CODE',
       'COUNTY', 'SITE_LATITUDE', 'SITE_LONGITUDE'],
      dtype='object')

In [23]:
#Check Null Values
Pb_2019.columns.isnull()

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False])

In [24]:
#Drop Columns
Pb_2019 = Pb_2019.drop(columns=['Date','Source','Site ID','POC' ,'UNITS','Site Name','AQS_PARAMETER_CODE','AQS_PARAMETER_DESC', 'CBSA_CODE','CBSA_NAME','STATE_CODE','STATE','COUNTY_CODE', 'COUNTY'], axis=1)

In [25]:
#Check DataFrame
Pb_2019.head()

Daily Mean Pb Concentration DAILY_AQI_VALUE  DAILY_OBS_COUNT  \
0                      0.00148               .                1   
1                      0.00387               .                1   
2                      0.00065               .                1   
3                      0.00065               .                1   
4                      0.00065               .                1   

   PERCENT_COMPLETE  SITE_LATITUDE  SITE_LONGITUDE  
0             100.0      37.765946     -122.399044  
1             100.0      37.765946     -122.399044  
2             100.0      37.765946     -122.399044  
3             100.0      37.765946     -122.399044  
4             100.0      37.765946     -122.399044

In [26]:
#Check count
Pb_2019.count()

Daily Mean Pb Concentration    28
DAILY_AQI_VALUE                28
DAILY_OBS_COUNT                28
PERCENT_COMPLETE               28
SITE_LATITUDE                  28
SITE_LONGITUDE                 28
dtype: int64

In [27]:
##Load CSV for PM2.5
file_to_load = ("SF 2019 PM2.5.csv")
PM2_5_2019 =pd.read_csv(file_to_load)
PM2_5_2019.head()

Date Source   Site ID  POC  Daily Mean PM2.5 Concentration     UNITS  \
0  01/01/2019    AQS  60010007    3                             5.7  ug/m3 LC   
1  01/02/2019    AQS  60010007    3                            11.9  ug/m3 LC   
2  01/03/2019    AQS  60010007    3                            20.1  ug/m3 LC   
3  01/04/2019    AQS  60010007    3                            28.8  ug/m3 LC   
4  01/05/2019    AQS  60010007    3                            11.2  ug/m3 LC   

   DAILY_AQI_VALUE  Site Name  DAILY_OBS_COUNT  PERCENT_COMPLETE  \
0               24  Livermore                1             100.0   
1               50  Livermore                1             100.0   
2               68  Livermore                1             100.0   
3               86  Livermore                1             100.0   
4               47  Livermore                1             100.0   

   AQS_PARAMETER_CODE        AQS_PARAMETER_DESC  CBSA_CODE  \
0               88101  PM2.5 - Local Conditions      41860   
1               88101  PM2.5 - Local Conditions      41860   
2               88101  PM2.5 - Local Conditions      41860   
3               88101  PM2.5 - Local Conditions      41860   
4               88101  PM2.5 - Local Conditions      41860   

                           CBSA_NAME  STATE_CODE       STATE  COUNTY_CODE  \
0  San Francisco-Oakland-Hayward, CA           6  California            1   
1  San Francisco-Oakland-Hayward, CA           6  California            1   
2  San Francisco-Oakland-Hayward, CA           6  California            1   
3  San Francisco-Oakland-Hayward, CA           6  California            1   
4  San Francisco-Oakland-Hayward, CA           6  California            1   

    COUNTY  SITE_LATITUDE  SITE_LONGITUDE  
0  Alameda      37.687526     -121.784217  
1  Alameda      37.687526     -121.784217  
2  Alameda      37.687526     -121.784217  
3  Alameda      37.687526     -121.784217  
4  Alameda      37.687526     -121.784217

In [28]:
#Check Columns
PM2_5_2019.columns

Index(['Date', 'Source', 'Site ID', 'POC', 'Daily Mean PM2.5 Concentration',
       'UNITS', 'DAILY_AQI_VALUE', 'Site Name', 'DAILY_OBS_COUNT',
       'PERCENT_COMPLETE', 'AQS_PARAMETER_CODE', 'AQS_PARAMETER_DESC',
       'CBSA_CODE', 'CBSA_NAME', 'STATE_CODE', 'STATE', 'COUNTY_CODE',
       'COUNTY', 'SITE_LATITUDE', 'SITE_LONGITUDE'],
      dtype='object')

In [29]:
#Check Null Values
PM2_5_2019.columns.isnull()

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False])

In [30]:
#Drop Columns
PM2_5_2019 = PM2_5_2019.drop(columns=['Date','Source','Site ID','POC' ,'UNITS','Site Name','AQS_PARAMETER_CODE','AQS_PARAMETER_DESC', 'CBSA_CODE','CBSA_NAME','STATE_CODE','STATE','COUNTY_CODE', 'COUNTY'], axis=1)

In [31]:
#Check DataFrame
PM2_5_2019.head()

Daily Mean PM2.5 Concentration  DAILY_AQI_VALUE  DAILY_OBS_COUNT  \
0                             5.7               24                1   
1                            11.9               50                1   
2                            20.1               68                1   
3                            28.8               86                1   
4                            11.2               47                1   

   PERCENT_COMPLETE  SITE_LATITUDE  SITE_LONGITUDE  
0             100.0      37.687526     -121.784217  
1             100.0      37.687526     -121.784217  
2             100.0      37.687526     -121.784217  
3             100.0      37.687526     -121.784217  
4             100.0      37.687526     -121.784217

In [32]:
#Check count
PM2_5_2019.count()

Daily Mean PM2.5 Concentration    4108
DAILY_AQI_VALUE                   4108
DAILY_OBS_COUNT                   4108
PERCENT_COMPLETE                  4108
SITE_LATITUDE                     4108
SITE_LONGITUDE                    4108
dtype: int64

In [37]:
##Load CSV for SO2
file_to_load = ("SF 2019 SO2.csv")
SO2_2019 =pd.read_csv(file_to_load)
SO2_2019.head()

Date Source   Site ID  POC  Daily Max 1-hour SO2 Concentration UNITS  \
0  01/01/2019    AQS  60010011    1                                 1.0   ppb   
1  01/02/2019    AQS  60010011    1                                 4.0   ppb   
2  01/03/2019    AQS  60010011    1                                 1.4   ppb   
3  01/04/2019    AQS  60010011    1                                 2.4   ppb   
4  01/05/2019    AQS  60010011    1                                 0.5   ppb   

   DAILY_AQI_VALUE     Site Name  DAILY_OBS_COUNT  PERCENT_COMPLETE  \
0                1  Oakland West               22              92.0   
1                6  Oakland West               22              92.0   
2                1  Oakland West               22              92.0   
3                3  Oakland West               22              92.0   
4                0  Oakland West               22              92.0   

   AQS_PARAMETER_CODE AQS_PARAMETER_DESC  CBSA_CODE  \
0               42401     Sulfur dioxide      41860   
1               42401     Sulfur dioxide      41860   
2               42401     Sulfur dioxide      41860   
3               42401     Sulfur dioxide      41860   
4               42401     Sulfur dioxide      41860   

                           CBSA_NAME  STATE_CODE       STATE  COUNTY_CODE  \
0  San Francisco-Oakland-Hayward, CA           6  California            1   
1  San Francisco-Oakland-Hayward, CA           6  California            1   
2  San Francisco-Oakland-Hayward, CA           6  California            1   
3  San Francisco-Oakland-Hayward, CA           6  California            1   
4  San Francisco-Oakland-Hayward, CA           6  California            1   

    COUNTY  SITE_LATITUDE  SITE_LONGITUDE  
0  Alameda      37.814781     -122.282347  
1  Alameda      37.814781     -122.282347  
2  Alameda      37.814781     -122.282347  
3  Alameda      37.814781     -122.282347  
4  Alameda      37.814781     -122.282347

In [38]:
#Check Columns
SO2_2019.columns

Index(['Date', 'Source', 'Site ID', 'POC',
       'Daily Max 1-hour SO2 Concentration', 'UNITS', 'DAILY_AQI_VALUE',
       'Site Name', 'DAILY_OBS_COUNT', 'PERCENT_COMPLETE',
       'AQS_PARAMETER_CODE', 'AQS_PARAMETER_DESC', 'CBSA_CODE', 'CBSA_NAME',
       'STATE_CODE', 'STATE', 'COUNTY_CODE', 'COUNTY', 'SITE_LATITUDE',
       'SITE_LONGITUDE'],
      dtype='object')

In [39]:
#Check Null Values
SO2_2019.columns.isnull()

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False])

In [40]:
#Drop Columns
SO2_2019 = SO2_2019.drop(columns=['Source','Site ID','POC','Site Name','AQS_PARAMETER_CODE','AQS_PARAMETER_DESC', 'CBSA_CODE','STATE_CODE','STATE','COUNTY_CODE'], axis=1)

In [41]:
#Check DataFrame
SO2_2019.head()

Date  Daily Max 1-hour SO2 Concentration UNITS  DAILY_AQI_VALUE  \
0  01/01/2019                                 1.0   ppb                1   
1  01/02/2019                                 4.0   ppb                6   
2  01/03/2019                                 1.4   ppb                1   
3  01/04/2019                                 2.4   ppb                3   
4  01/05/2019                                 0.5   ppb                0   

   DAILY_OBS_COUNT  PERCENT_COMPLETE                          CBSA_NAME  \
0               22              92.0  San Francisco-Oakland-Hayward, CA   
1               22              92.0  San Francisco-Oakland-Hayward, CA   
2               22              92.0  San Francisco-Oakland-Hayward, CA   
3               22              92.0  San Francisco-Oakland-Hayward, CA   
4               22              92.0  San Francisco-Oakland-Hayward, CA   

    COUNTY  SITE_LATITUDE  SITE_LONGITUDE  
0  Alameda      37.814781     -122.282347  
1  Alameda      37.814781     -122.282347  
2  Alameda      37.814781     -122.282347  
3  Alameda      37.814781     -122.282347  
4  Alameda      37.814781     -122.282347

In [42]:
#Check Count
SO2_2019.count()

Date                                  2488
Daily Max 1-hour SO2 Concentration    2488
UNITS                                 2488
DAILY_AQI_VALUE                       2488
DAILY_OBS_COUNT                       2488
PERCENT_COMPLETE                      2488
CBSA_NAME                             2488
COUNTY                                2488
SITE_LATITUDE                         2488
SITE_LONGITUDE                        2488
dtype: int64

In [43]:
##Load CSV for PM2.5
file_to_load = ("SF 2019 PM10.csv")
PM10_2019 =pd.read_csv(file_to_load)
PM10_2019.head()

Date Source   Site ID  POC  Daily Mean PM10 Concentration     UNITS  \
0  01/09/2019    AQS  60130002    1                              6  ug/m3 SC   
1  01/21/2019    AQS  60130002    1                              6  ug/m3 SC   
2  02/02/2019    AQS  60130002    1                              2  ug/m3 SC   
3  02/14/2019    AQS  60130002    1                              4  ug/m3 SC   
4  02/26/2019    AQS  60130002    1                              4  ug/m3 SC   

   DAILY_AQI_VALUE Site Name  DAILY_OBS_COUNT  PERCENT_COMPLETE  \
0                6   Concord                1             100.0   
1                6   Concord                1             100.0   
2                2   Concord                1             100.0   
3                4   Concord                1             100.0   
4                4   Concord                1             100.0   

   AQS_PARAMETER_CODE     AQS_PARAMETER_DESC  CBSA_CODE  \
0               81102  PM10 Total 0-10um STP      41860   
1               81102  PM10 Total 0-10um STP      41860   
2               81102  PM10 Total 0-10um STP      41860   
3               81102  PM10 Total 0-10um STP      41860   
4               81102  PM10 Total 0-10um STP      41860   

                           CBSA_NAME  STATE_CODE       STATE  COUNTY_CODE  \
0  San Francisco-Oakland-Hayward, CA           6  California           13   
1  San Francisco-Oakland-Hayward, CA           6  California           13   
2  San Francisco-Oakland-Hayward, CA           6  California           13   
3  San Francisco-Oakland-Hayward, CA           6  California           13   
4  San Francisco-Oakland-Hayward, CA           6  California           13   

         COUNTY  SITE_LATITUDE  SITE_LONGITUDE  
0  Contra Costa      37.936013     -122.026154  
1  Contra Costa      37.936013     -122.026154  
2  Contra Costa      37.936013     -122.026154  
3  Contra Costa      37.936013     -122.026154  
4  Contra Costa      37.936013     -122.026154

In [44]:
#Check Columns
PM10_2019.columns

Index(['Date', 'Source', 'Site ID', 'POC', 'Daily Mean PM10 Concentration',
       'UNITS', 'DAILY_AQI_VALUE', 'Site Name', 'DAILY_OBS_COUNT',
       'PERCENT_COMPLETE', 'AQS_PARAMETER_CODE', 'AQS_PARAMETER_DESC',
       'CBSA_CODE', 'CBSA_NAME', 'STATE_CODE', 'STATE', 'COUNTY_CODE',
       'COUNTY', 'SITE_LATITUDE', 'SITE_LONGITUDE'],
      dtype='object')

In [45]:
#Check Null Values
PM10_2019.columns.isnull()

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False])

In [46]:
#Drop Columns
PM10_2019 = PM10_2019.drop(columns=['Source','Site ID','POC','Site Name','AQS_PARAMETER_CODE','AQS_PARAMETER_DESC', 'CBSA_CODE','STATE_CODE','STATE','COUNTY_CODE'], axis=1)

In [47]:
#Check DataFrame
PM10_2019.head()

Date  Daily Mean PM10 Concentration     UNITS  DAILY_AQI_VALUE  \
0  01/09/2019                              6  ug/m3 SC                6   
1  01/21/2019                              6  ug/m3 SC                6   
2  02/02/2019                              2  ug/m3 SC                2   
3  02/14/2019                              4  ug/m3 SC                4   
4  02/26/2019                              4  ug/m3 SC                4   

   DAILY_OBS_COUNT  PERCENT_COMPLETE                          CBSA_NAME  \
0                1             100.0  San Francisco-Oakland-Hayward, CA   
1                1             100.0  San Francisco-Oakland-Hayward, CA   
2                1             100.0  San Francisco-Oakland-Hayward, CA   
3                1             100.0  San Francisco-Oakland-Hayward, CA   
4                1             100.0  San Francisco-Oakland-Hayward, CA   

         COUNTY  SITE_LATITUDE  SITE_LONGITUDE  
0  Contra Costa      37.936013     -122.026154  
1  Contra Costa      37.936013     -122.026154  
2  Contra Costa      37.936013     -122.026154  
3  Contra Costa      37.936013     -122.026154  
4  Contra Costa      37.936013     -122.026154

In [48]:
#Check Count
PM10_2019.count()

Date                             267
Daily Mean PM10 Concentration    267
UNITS                            267
DAILY_AQI_VALUE                  267
DAILY_OBS_COUNT                  267
PERCENT_COMPLETE                 267
CBSA_NAME                        267
COUNTY                           267
SITE_LATITUDE                    267
SITE_LONGITUDE                   267
dtype: int64