In [1]:
#Import dependencies
import pandas as pd
import os
import numpy as np

In [3]:
#Load CSV
file_to_load = ("SF 2020 CO.csv")
SF_2020_CO =pd.read_csv(file_to_load)
SF_2020_CO.head()

Date Source   Site ID  POC  Daily Max 8-hour CO Concentration UNITS  \
0  01/01/2020    AQS  60010009    1                                0.7   ppm   
1  01/02/2020    AQS  60010009    1                                0.7   ppm   
2  01/03/2020    AQS  60010009    1                                0.9   ppm   
3  01/04/2020    AQS  60010009    1                                0.8   ppm   
4  01/05/2020    AQS  60010009    1                                0.7   ppm   

   DAILY_AQI_VALUE Site Name  DAILY_OBS_COUNT  PERCENT_COMPLETE  \
0                8   Oakland               18              75.0   
1                8   Oakland               24             100.0   
2               10   Oakland               24             100.0   
3                9   Oakland               24             100.0   
4                8   Oakland               24             100.0   

   AQS_PARAMETER_CODE AQS_PARAMETER_DESC  CBSA_CODE  \
0               42101    Carbon monoxide      41860   
1               42101    Carbon monoxide      41860   
2               42101    Carbon monoxide      41860   
3               42101    Carbon monoxide      41860   
4               42101    Carbon monoxide      41860   

                           CBSA_NAME  STATE_CODE       STATE  COUNTY_CODE  \
0  San Francisco-Oakland-Hayward, CA           6  California            1   
1  San Francisco-Oakland-Hayward, CA           6  California            1   
2  San Francisco-Oakland-Hayward, CA           6  California            1   
3  San Francisco-Oakland-Hayward, CA           6  California            1   
4  San Francisco-Oakland-Hayward, CA           6  California            1   

    COUNTY  SITE_LATITUDE  SITE_LONGITUDE  
0  Alameda      37.743065     -122.169935  
1  Alameda      37.743065     -122.169935  
2  Alameda      37.743065     -122.169935  
3  Alameda      37.743065     -122.169935  
4  Alameda      37.743065     -122.169935

In [4]:
#Check Columns
SF_2020_CO.columns

Index(['Date', 'Source', 'Site ID', 'POC', 'Daily Max 8-hour CO Concentration',
       'UNITS', 'DAILY_AQI_VALUE', 'Site Name', 'DAILY_OBS_COUNT',
       'PERCENT_COMPLETE', 'AQS_PARAMETER_CODE', 'AQS_PARAMETER_DESC',
       'CBSA_CODE', 'CBSA_NAME', 'STATE_CODE', 'STATE', 'COUNTY_CODE',
       'COUNTY', 'SITE_LATITUDE', 'SITE_LONGITUDE'],
      dtype='object')

In [5]:
#Check Null Values
SF_2020_CO.columns.isnull()

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False])

In [6]:
#Drop Columns
SF_2020_CO= SF_2020_CO.drop(columns=['Source','Site ID','POC','Site Name','AQS_PARAMETER_CODE','AQS_PARAMETER_DESC', 'CBSA_CODE','STATE_CODE','STATE','COUNTY_CODE'], axis=1)

In [7]:
#Check DataFrame
SF_2020_CO.head()

Date  Daily Max 8-hour CO Concentration UNITS  DAILY_AQI_VALUE  \
0  01/01/2020                                0.7   ppm                8   
1  01/02/2020                                0.7   ppm                8   
2  01/03/2020                                0.9   ppm               10   
3  01/04/2020                                0.8   ppm                9   
4  01/05/2020                                0.7   ppm                8   

   DAILY_OBS_COUNT  PERCENT_COMPLETE                          CBSA_NAME  \
0               18              75.0  San Francisco-Oakland-Hayward, CA   
1               24             100.0  San Francisco-Oakland-Hayward, CA   
2               24             100.0  San Francisco-Oakland-Hayward, CA   
3               24             100.0  San Francisco-Oakland-Hayward, CA   
4               24             100.0  San Francisco-Oakland-Hayward, CA   

    COUNTY  SITE_LATITUDE  SITE_LONGITUDE  
0  Alameda      37.743065     -122.169935  
1  Alameda      37.743065     -122.169935  
2  Alameda      37.743065     -122.169935  
3  Alameda      37.743065     -122.169935  
4  Alameda      37.743065     -122.169935

In [8]:
#Check Count
SF_2020_CO.count()

Date                                 3959
Daily Max 8-hour CO Concentration    3959
UNITS                                3959
DAILY_AQI_VALUE                      3959
DAILY_OBS_COUNT                      3959
PERCENT_COMPLETE                     3959
CBSA_NAME                            3959
COUNTY                               3959
SITE_LATITUDE                        3959
SITE_LONGITUDE                       3959
dtype: int64

In [9]:
##Load CSV for NO2
file_to_load = ("SF 2020 NO2.csv")
NO2_2020 =pd.read_csv(file_to_load)
NO2_2020.head()

Date Source   Site ID  POC  Daily Max 1-hour NO2 Concentration UNITS  \
0  01/01/2020    AQS  60010007    1                                18.5   ppb   
1  01/02/2020    AQS  60010007    1                                22.7   ppb   
2  01/03/2020    AQS  60010007    1                                23.6   ppb   
3  01/04/2020    AQS  60010007    1                                21.2   ppb   
4  01/05/2020    AQS  60010007    1                                23.0   ppb   

   DAILY_AQI_VALUE  Site Name  DAILY_OBS_COUNT  PERCENT_COMPLETE  \
0               17  Livermore               23              96.0   
1               21  Livermore               23              96.0   
2               22  Livermore               23              96.0   
3               20  Livermore               23              96.0   
4               22  Livermore               23              96.0   

   AQS_PARAMETER_CODE      AQS_PARAMETER_DESC  CBSA_CODE  \
0               42602  Nitrogen dioxide (NO2)      41860   
1               42602  Nitrogen dioxide (NO2)      41860   
2               42602  Nitrogen dioxide (NO2)      41860   
3               42602  Nitrogen dioxide (NO2)      41860   
4               42602  Nitrogen dioxide (NO2)      41860   

                           CBSA_NAME  STATE_CODE       STATE  COUNTY_CODE  \
0  San Francisco-Oakland-Hayward, CA           6  California            1   
1  San Francisco-Oakland-Hayward, CA           6  California            1   
2  San Francisco-Oakland-Hayward, CA           6  California            1   
3  San Francisco-Oakland-Hayward, CA           6  California            1   
4  San Francisco-Oakland-Hayward, CA           6  California            1   

    COUNTY  SITE_LATITUDE  SITE_LONGITUDE  
0  Alameda      37.687526     -121.784217  
1  Alameda      37.687526     -121.784217  
2  Alameda      37.687526     -121.784217  
3  Alameda      37.687526     -121.784217  
4  Alameda      37.687526     -121.784217

In [10]:
#Check Columns
NO2_2020.columns

Index(['Date', 'Source', 'Site ID', 'POC',
       'Daily Max 1-hour NO2 Concentration', 'UNITS', 'DAILY_AQI_VALUE',
       'Site Name', 'DAILY_OBS_COUNT', 'PERCENT_COMPLETE',
       'AQS_PARAMETER_CODE', 'AQS_PARAMETER_DESC', 'CBSA_CODE', 'CBSA_NAME',
       'STATE_CODE', 'STATE', 'COUNTY_CODE', 'COUNTY', 'SITE_LATITUDE',
       'SITE_LONGITUDE'],
      dtype='object')

In [11]:
#Check Null Values
NO2_2020.columns.isnull()

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False])

In [12]:
#Drop Columns
NO2_2020 = NO2_2020.drop(columns=['Source','Site ID','POC','Site Name','AQS_PARAMETER_CODE','AQS_PARAMETER_DESC', 'CBSA_CODE','STATE_CODE','STATE','COUNTY_CODE'], axis=1)

In [13]:
#Check DataFrame
NO2_2020.head()

Date  Daily Max 1-hour NO2 Concentration UNITS  DAILY_AQI_VALUE  \
0  01/01/2020                                18.5   ppb               17   
1  01/02/2020                                22.7   ppb               21   
2  01/03/2020                                23.6   ppb               22   
3  01/04/2020                                21.2   ppb               20   
4  01/05/2020                                23.0   ppb               22   

   DAILY_OBS_COUNT  PERCENT_COMPLETE                          CBSA_NAME  \
0               23              96.0  San Francisco-Oakland-Hayward, CA   
1               23              96.0  San Francisco-Oakland-Hayward, CA   
2               23              96.0  San Francisco-Oakland-Hayward, CA   
3               23              96.0  San Francisco-Oakland-Hayward, CA   
4               23              96.0  San Francisco-Oakland-Hayward, CA   

    COUNTY  SITE_LATITUDE  SITE_LONGITUDE  
0  Alameda      37.687526     -121.784217  
1  Alameda      37.687526     -121.784217  
2  Alameda      37.687526     -121.784217  
3  Alameda      37.687526     -121.784217  
4  Alameda      37.687526     -121.784217

In [14]:
#Check Count
NO2_2020.count()

Date                                  4610
Daily Max 1-hour NO2 Concentration    4610
UNITS                                 4610
DAILY_AQI_VALUE                       4610
DAILY_OBS_COUNT                       4610
PERCENT_COMPLETE                      4610
CBSA_NAME                             4610
COUNTY                                4610
SITE_LATITUDE                         4610
SITE_LONGITUDE                        4610
dtype: int64

In [15]:
##Load CSV for Ozone
file_to_load = ("SF 2020 Ozone.csv")
Ozone_2020 =pd.read_csv(file_to_load)
Ozone_2020.head()

Date Source   Site ID  POC  Daily Max 8-hour Ozone Concentration  \
0  01/01/2020    AQS  60010007    1                                 0.025   
1  01/02/2020    AQS  60010007    1                                 0.017   
2  01/03/2020    AQS  60010007    1                                 0.013   
3  01/04/2020    AQS  60010007    1                                 0.028   
4  01/05/2020    AQS  60010007    1                                 0.031   

  UNITS  DAILY_AQI_VALUE  Site Name  DAILY_OBS_COUNT  PERCENT_COMPLETE  \
0   ppm               23  Livermore               17             100.0   
1   ppm               16  Livermore               17             100.0   
2   ppm               12  Livermore               17             100.0   
3   ppm               26  Livermore               17             100.0   
4   ppm               29  Livermore               17             100.0   

   AQS_PARAMETER_CODE AQS_PARAMETER_DESC  CBSA_CODE  \
0               44201              Ozone      41860   
1               44201              Ozone      41860   
2               44201              Ozone      41860   
3               44201              Ozone      41860   
4               44201              Ozone      41860   

                           CBSA_NAME  STATE_CODE       STATE  COUNTY_CODE  \
0  San Francisco-Oakland-Hayward, CA           6  California            1   
1  San Francisco-Oakland-Hayward, CA           6  California            1   
2  San Francisco-Oakland-Hayward, CA           6  California            1   
3  San Francisco-Oakland-Hayward, CA           6  California            1   
4  San Francisco-Oakland-Hayward, CA           6  California            1   

    COUNTY  SITE_LATITUDE  SITE_LONGITUDE  
0  Alameda      37.687526     -121.784217  
1  Alameda      37.687526     -121.784217  
2  Alameda      37.687526     -121.784217  
3  Alameda      37.687526     -121.784217  
4  Alameda      37.687526     -121.784217

In [16]:
#Check Columns
Ozone_2020.columns

Index(['Date', 'Source', 'Site ID', 'POC',
       'Daily Max 8-hour Ozone Concentration', 'UNITS', 'DAILY_AQI_VALUE',
       'Site Name', 'DAILY_OBS_COUNT', 'PERCENT_COMPLETE',
       'AQS_PARAMETER_CODE', 'AQS_PARAMETER_DESC', 'CBSA_CODE', 'CBSA_NAME',
       'STATE_CODE', 'STATE', 'COUNTY_CODE', 'COUNTY', 'SITE_LATITUDE',
       'SITE_LONGITUDE'],
      dtype='object')

In [17]:
#Check Null Values
Ozone_2020.columns.isnull()

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False])

In [18]:
#Drop Columns
Ozone_2020 = Ozone_2020.drop(columns=['Source','Site ID','POC','Site Name','AQS_PARAMETER_CODE','AQS_PARAMETER_DESC', 'CBSA_CODE','STATE_CODE','STATE','COUNTY_CODE'], axis=1)

In [19]:
#Check DataFrame
Ozone_2020.head()

Date  Daily Max 8-hour Ozone Concentration UNITS  DAILY_AQI_VALUE  \
0  01/01/2020                                 0.025   ppm               23   
1  01/02/2020                                 0.017   ppm               16   
2  01/03/2020                                 0.013   ppm               12   
3  01/04/2020                                 0.028   ppm               26   
4  01/05/2020                                 0.031   ppm               29   

   DAILY_OBS_COUNT  PERCENT_COMPLETE                          CBSA_NAME  \
0               17             100.0  San Francisco-Oakland-Hayward, CA   
1               17             100.0  San Francisco-Oakland-Hayward, CA   
2               17             100.0  San Francisco-Oakland-Hayward, CA   
3               17             100.0  San Francisco-Oakland-Hayward, CA   
4               17             100.0  San Francisco-Oakland-Hayward, CA   

    COUNTY  SITE_LATITUDE  SITE_LONGITUDE  
0  Alameda      37.687526     -121.784217  
1  Alameda      37.687526     -121.784217  
2  Alameda      37.687526     -121.784217  
3  Alameda      37.687526     -121.784217  
4  Alameda      37.687526     -121.784217

In [20]:
#Check count
Ozone_2020.count()

Date                                    4353
Daily Max 8-hour Ozone Concentration    4353
UNITS                                   4353
DAILY_AQI_VALUE                         4353
DAILY_OBS_COUNT                         4353
PERCENT_COMPLETE                        4353
CBSA_NAME                               4353
COUNTY                                  4353
SITE_LATITUDE                           4353
SITE_LONGITUDE                          4353
dtype: int64

In [21]:
##Load CSV for Pb
file_to_load = ("SF 2020 Pb.csv")
Pb_2020 =pd.read_csv(file_to_load)
Pb_2020.head()

Date Source   Site ID  POC  Daily Mean Pb Concentration     UNITS  \
0  01/04/2020    AQS  60750005    7                      0.00227  ug/m3 SC   
1  01/16/2020    AQS  60750005    7                      0.00145  ug/m3 SC   
2  01/28/2020    AQS  60750005    7                      0.00230  ug/m3 SC   
3  02/09/2020    AQS  60750005    7                      0.00735  ug/m3 SC   
4  02/21/2020    AQS  60750005    7                      0.00803  ug/m3 SC   

  DAILY_AQI_VALUE      Site Name  DAILY_OBS_COUNT  PERCENT_COMPLETE  \
0               .  San Francisco                1             100.0   
1               .  San Francisco                1             100.0   
2               .  San Francisco                1             100.0   
3               .  San Francisco                1             100.0   
4               .  San Francisco                1             100.0   

   AQS_PARAMETER_CODE AQS_PARAMETER_DESC  CBSA_CODE  \
0               12128     Lead (TSP) STP      41860   
1               12128     Lead (TSP) STP      41860   
2               12128     Lead (TSP) STP      41860   
3               12128     Lead (TSP) STP      41860   
4               12128     Lead (TSP) STP      41860   

                           CBSA_NAME  STATE_CODE       STATE  COUNTY_CODE  \
0  San Francisco-Oakland-Hayward, CA           6  California           75   
1  San Francisco-Oakland-Hayward, CA           6  California           75   
2  San Francisco-Oakland-Hayward, CA           6  California           75   
3  San Francisco-Oakland-Hayward, CA           6  California           75   
4  San Francisco-Oakland-Hayward, CA           6  California           75   

          COUNTY  SITE_LATITUDE  SITE_LONGITUDE  
0  San Francisco      37.765946     -122.399044  
1  San Francisco      37.765946     -122.399044  
2  San Francisco      37.765946     -122.399044  
3  San Francisco      37.765946     -122.399044  
4  San Francisco      37.765946     -122.399044

In [22]:
#Check Columns
Pb_2020.columns

Index(['Date', 'Source', 'Site ID', 'POC', 'Daily Mean Pb Concentration',
       'UNITS', 'DAILY_AQI_VALUE', 'Site Name', 'DAILY_OBS_COUNT',
       'PERCENT_COMPLETE', 'AQS_PARAMETER_CODE', 'AQS_PARAMETER_DESC',
       'CBSA_CODE', 'CBSA_NAME', 'STATE_CODE', 'STATE', 'COUNTY_CODE',
       'COUNTY', 'SITE_LATITUDE', 'SITE_LONGITUDE'],
      dtype='object')

In [23]:
#Check Null Values
Pb_2020.columns.isnull()

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False])

In [24]:
#Drop Columns
Pb_2020 = Pb_2020.drop(columns=['Source','Site ID','POC','Site Name','AQS_PARAMETER_CODE','AQS_PARAMETER_DESC', 'CBSA_CODE','STATE_CODE','STATE','COUNTY_CODE'], axis=1)

In [25]:
#Check DataFrame
Pb_2020.head()

Date  Daily Mean Pb Concentration     UNITS DAILY_AQI_VALUE  \
0  01/04/2020                      0.00227  ug/m3 SC               .   
1  01/16/2020                      0.00145  ug/m3 SC               .   
2  01/28/2020                      0.00230  ug/m3 SC               .   
3  02/09/2020                      0.00735  ug/m3 SC               .   
4  02/21/2020                      0.00803  ug/m3 SC               .   

   DAILY_OBS_COUNT  PERCENT_COMPLETE                          CBSA_NAME  \
0                1             100.0  San Francisco-Oakland-Hayward, CA   
1                1             100.0  San Francisco-Oakland-Hayward, CA   
2                1             100.0  San Francisco-Oakland-Hayward, CA   
3                1             100.0  San Francisco-Oakland-Hayward, CA   
4                1             100.0  San Francisco-Oakland-Hayward, CA   

          COUNTY  SITE_LATITUDE  SITE_LONGITUDE  
0  San Francisco      37.765946     -122.399044  
1  San Francisco      37.765946     -122.399044  
2  San Francisco      37.765946     -122.399044  
3  San Francisco      37.765946     -122.399044  
4  San Francisco      37.765946     -122.399044

In [26]:
#Check count
Pb_2020.count()

Date                           9
Daily Mean Pb Concentration    9
UNITS                          9
DAILY_AQI_VALUE                9
DAILY_OBS_COUNT                9
PERCENT_COMPLETE               9
CBSA_NAME                      9
COUNTY                         9
SITE_LATITUDE                  9
SITE_LONGITUDE                 9
dtype: int64

In [27]:
##Load CSV for PM2.5
file_to_load = ("SF 2020 PM2.5.csv")
PM2_5_2020 =pd.read_csv(file_to_load)
PM2_5_2020.head()

Date Source   Site ID  POC  Daily Mean PM2.5 Concentration     UNITS  \
0  01/01/2020    AQS  60010007    3                             8.6  ug/m3 LC   
1  01/02/2020    AQS  60010007    3                             4.5  ug/m3 LC   
2  01/03/2020    AQS  60010007    3                            14.2  ug/m3 LC   
3  01/04/2020    AQS  60010007    3                            10.9  ug/m3 LC   
4  01/05/2020    AQS  60010007    3                             7.8  ug/m3 LC   

   DAILY_AQI_VALUE  Site Name  DAILY_OBS_COUNT  PERCENT_COMPLETE  \
0               36  Livermore                1             100.0   
1               19  Livermore                1             100.0   
2               55  Livermore                1             100.0   
3               45  Livermore                1             100.0   
4               33  Livermore                1             100.0   

   AQS_PARAMETER_CODE        AQS_PARAMETER_DESC  CBSA_CODE  \
0               88101  PM2.5 - Local Conditions      41860   
1               88101  PM2.5 - Local Conditions      41860   
2               88101  PM2.5 - Local Conditions      41860   
3               88101  PM2.5 - Local Conditions      41860   
4               88101  PM2.5 - Local Conditions      41860   

                           CBSA_NAME  STATE_CODE       STATE  COUNTY_CODE  \
0  San Francisco-Oakland-Hayward, CA           6  California            1   
1  San Francisco-Oakland-Hayward, CA           6  California            1   
2  San Francisco-Oakland-Hayward, CA           6  California            1   
3  San Francisco-Oakland-Hayward, CA           6  California            1   
4  San Francisco-Oakland-Hayward, CA           6  California            1   

    COUNTY  SITE_LATITUDE  SITE_LONGITUDE  
0  Alameda      37.687526     -121.784217  
1  Alameda      37.687526     -121.784217  
2  Alameda      37.687526     -121.784217  
3  Alameda      37.687526     -121.784217  
4  Alameda      37.687526     -121.784217

In [28]:
#Check Columns
PM2_5_2020.columns

Index(['Date', 'Source', 'Site ID', 'POC', 'Daily Mean PM2.5 Concentration',
       'UNITS', 'DAILY_AQI_VALUE', 'Site Name', 'DAILY_OBS_COUNT',
       'PERCENT_COMPLETE', 'AQS_PARAMETER_CODE', 'AQS_PARAMETER_DESC',
       'CBSA_CODE', 'CBSA_NAME', 'STATE_CODE', 'STATE', 'COUNTY_CODE',
       'COUNTY', 'SITE_LATITUDE', 'SITE_LONGITUDE'],
      dtype='object')

In [29]:
#Check Null Values
PM2_5_2020.columns.isnull()

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False])

In [30]:
#Drop Columns
PM2_5_2020 = PM2_5_2020.drop(columns=['Source','Site ID','POC','Site Name','AQS_PARAMETER_CODE','AQS_PARAMETER_DESC', 'CBSA_CODE','STATE_CODE','STATE','COUNTY_CODE'], axis=1)

In [31]:
#Check DataFrame
PM2_5_2020.head()

Date  Daily Mean PM2.5 Concentration     UNITS  DAILY_AQI_VALUE  \
0  01/01/2020                             8.6  ug/m3 LC               36   
1  01/02/2020                             4.5  ug/m3 LC               19   
2  01/03/2020                            14.2  ug/m3 LC               55   
3  01/04/2020                            10.9  ug/m3 LC               45   
4  01/05/2020                             7.8  ug/m3 LC               33   

   DAILY_OBS_COUNT  PERCENT_COMPLETE                          CBSA_NAME  \
0                1             100.0  San Francisco-Oakland-Hayward, CA   
1                1             100.0  San Francisco-Oakland-Hayward, CA   
2                1             100.0  San Francisco-Oakland-Hayward, CA   
3                1             100.0  San Francisco-Oakland-Hayward, CA   
4                1             100.0  San Francisco-Oakland-Hayward, CA   

    COUNTY  SITE_LATITUDE  SITE_LONGITUDE  
0  Alameda      37.687526     -121.784217  
1  Alameda      37.687526     -121.784217  
2  Alameda      37.687526     -121.784217  
3  Alameda      37.687526     -121.784217  
4  Alameda      37.687526     -121.784217

In [32]:
#Check count
PM2_5_2020.count()

Date                              4099
Daily Mean PM2.5 Concentration    4099
UNITS                             4099
DAILY_AQI_VALUE                   4099
DAILY_OBS_COUNT                   4099
PERCENT_COMPLETE                  4099
CBSA_NAME                         4099
COUNTY                            4099
SITE_LATITUDE                     4099
SITE_LONGITUDE                    4099
dtype: int64

In [33]:
##Load CSV for SO2
file_to_load = ("SF 2020 SO2.csv")
SO2_2020 =pd.read_csv(file_to_load)
SO2_2020.head()

Date Source   Site ID  POC  Daily Max 1-hour SO2 Concentration UNITS  \
0  01/01/2020    AQS  60010011    1                                 0.5   ppb   
1  01/02/2020    AQS  60010011    1                                 1.2   ppb   
2  01/03/2020    AQS  60010011    1                                 1.8   ppb   
3  01/04/2020    AQS  60010011    1                                 1.4   ppb   
4  01/05/2020    AQS  60010011    1                                 0.7   ppb   

   DAILY_AQI_VALUE     Site Name  DAILY_OBS_COUNT  PERCENT_COMPLETE  \
0                0  Oakland West               22              92.0   
1                1  Oakland West               22              92.0   
2                1  Oakland West               19              79.0   
3                1  Oakland West               22              92.0   
4                0  Oakland West               22              92.0   

   AQS_PARAMETER_CODE AQS_PARAMETER_DESC  CBSA_CODE  \
0               42401     Sulfur dioxide      41860   
1               42401     Sulfur dioxide      41860   
2               42401     Sulfur dioxide      41860   
3               42401     Sulfur dioxide      41860   
4               42401     Sulfur dioxide      41860   

                           CBSA_NAME  STATE_CODE       STATE  COUNTY_CODE  \
0  San Francisco-Oakland-Hayward, CA           6  California            1   
1  San Francisco-Oakland-Hayward, CA           6  California            1   
2  San Francisco-Oakland-Hayward, CA           6  California            1   
3  San Francisco-Oakland-Hayward, CA           6  California            1   
4  San Francisco-Oakland-Hayward, CA           6  California            1   

    COUNTY  SITE_LATITUDE  SITE_LONGITUDE  
0  Alameda      37.814781     -122.282347  
1  Alameda      37.814781     -122.282347  
2  Alameda      37.814781     -122.282347  
3  Alameda      37.814781     -122.282347  
4  Alameda      37.814781     -122.282347

In [34]:
#Check Columns
SO2_2020.columns

Index(['Date', 'Source', 'Site ID', 'POC',
       'Daily Max 1-hour SO2 Concentration', 'UNITS', 'DAILY_AQI_VALUE',
       'Site Name', 'DAILY_OBS_COUNT', 'PERCENT_COMPLETE',
       'AQS_PARAMETER_CODE', 'AQS_PARAMETER_DESC', 'CBSA_CODE', 'CBSA_NAME',
       'STATE_CODE', 'STATE', 'COUNTY_CODE', 'COUNTY', 'SITE_LATITUDE',
       'SITE_LONGITUDE'],
      dtype='object')

In [35]:
#Check Null Values
SO2_2020.columns.isnull()

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False])

In [36]:
#Drop Columns
SO2_2020 = SO2_2020.drop(columns=['Source','Site ID','POC','Site Name','AQS_PARAMETER_CODE','AQS_PARAMETER_DESC', 'CBSA_CODE','STATE_CODE','STATE','COUNTY_CODE'], axis=1)

In [37]:
#Check DataFrame
SO2_2020.head()

Date  Daily Max 1-hour SO2 Concentration UNITS  DAILY_AQI_VALUE  \
0  01/01/2020                                 0.5   ppb                0   
1  01/02/2020                                 1.2   ppb                1   
2  01/03/2020                                 1.8   ppb                1   
3  01/04/2020                                 1.4   ppb                1   
4  01/05/2020                                 0.7   ppb                0   

   DAILY_OBS_COUNT  PERCENT_COMPLETE                          CBSA_NAME  \
0               22              92.0  San Francisco-Oakland-Hayward, CA   
1               22              92.0  San Francisco-Oakland-Hayward, CA   
2               19              79.0  San Francisco-Oakland-Hayward, CA   
3               22              92.0  San Francisco-Oakland-Hayward, CA   
4               22              92.0  San Francisco-Oakland-Hayward, CA   

    COUNTY  SITE_LATITUDE  SITE_LONGITUDE  
0  Alameda      37.814781     -122.282347  
1  Alameda      37.814781     -122.282347  
2  Alameda      37.814781     -122.282347  
3  Alameda      37.814781     -122.282347  
4  Alameda      37.814781     -122.282347

In [38]:
#Check Count
SO2_2020.count()

Date                                  2368
Daily Max 1-hour SO2 Concentration    2368
UNITS                                 2368
DAILY_AQI_VALUE                       2368
DAILY_OBS_COUNT                       2368
PERCENT_COMPLETE                      2368
CBSA_NAME                             2368
COUNTY                                2368
SITE_LATITUDE                         2368
SITE_LONGITUDE                        2368
dtype: int64

In [39]:
##Load CSV for PM2.5
file_to_load = ("SF 2020 PM10.csv")
PM10_2020 =pd.read_csv(file_to_load)
PM10_2020.head()

Date Source   Site ID  POC  Daily Mean PM10 Concentration     UNITS  \
0  01/04/2020    AQS  60130002    1                             10  ug/m3 SC   
1  01/16/2020    AQS  60130002    1                              3  ug/m3 SC   
2  01/28/2020    AQS  60130002    1                              9  ug/m3 SC   
3  02/09/2020    AQS  60130002    1                              7  ug/m3 SC   
4  02/21/2020    AQS  60130002    1                             17  ug/m3 SC   

   DAILY_AQI_VALUE Site Name  DAILY_OBS_COUNT  PERCENT_COMPLETE  \
0                9   Concord                1             100.0   
1                3   Concord                1             100.0   
2                8   Concord                1             100.0   
3                6   Concord                1             100.0   
4               16   Concord                1             100.0   

   AQS_PARAMETER_CODE     AQS_PARAMETER_DESC  CBSA_CODE  \
0               81102  PM10 Total 0-10um STP      41860   
1               81102  PM10 Total 0-10um STP      41860   
2               81102  PM10 Total 0-10um STP      41860   
3               81102  PM10 Total 0-10um STP      41860   
4               81102  PM10 Total 0-10um STP      41860   

                           CBSA_NAME  STATE_CODE       STATE  COUNTY_CODE  \
0  San Francisco-Oakland-Hayward, CA           6  California           13   
1  San Francisco-Oakland-Hayward, CA           6  California           13   
2  San Francisco-Oakland-Hayward, CA           6  California           13   
3  San Francisco-Oakland-Hayward, CA           6  California           13   
4  San Francisco-Oakland-Hayward, CA           6  California           13   

         COUNTY  SITE_LATITUDE  SITE_LONGITUDE  
0  Contra Costa      37.936013     -122.026154  
1  Contra Costa      37.936013     -122.026154  
2  Contra Costa      37.936013     -122.026154  
3  Contra Costa      37.936013     -122.026154  
4  Contra Costa      37.936013     -122.026154

In [40]:
#Check Columns
PM10_2020.columns

Index(['Date', 'Source', 'Site ID', 'POC', 'Daily Mean PM10 Concentration',
       'UNITS', 'DAILY_AQI_VALUE', 'Site Name', 'DAILY_OBS_COUNT',
       'PERCENT_COMPLETE', 'AQS_PARAMETER_CODE', 'AQS_PARAMETER_DESC',
       'CBSA_CODE', 'CBSA_NAME', 'STATE_CODE', 'STATE', 'COUNTY_CODE',
       'COUNTY', 'SITE_LATITUDE', 'SITE_LONGITUDE'],
      dtype='object')

In [41]:
#Check Null Values
PM10_2020.columns.isnull()

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False])

In [42]:
#Drop Columns
PM10_2020 = PM10_2020.drop(columns=['Source','Site ID','POC','Site Name','AQS_PARAMETER_CODE','AQS_PARAMETER_DESC', 'CBSA_CODE','STATE_CODE','STATE','COUNTY_CODE'], axis=1)

In [43]:
#Check DataFrame 
PM10_2020.head()

Date  Daily Mean PM10 Concentration     UNITS  DAILY_AQI_VALUE  \
0  01/04/2020                             10  ug/m3 SC                9   
1  01/16/2020                              3  ug/m3 SC                3   
2  01/28/2020                              9  ug/m3 SC                8   
3  02/09/2020                              7  ug/m3 SC                6   
4  02/21/2020                             17  ug/m3 SC               16   

   DAILY_OBS_COUNT  PERCENT_COMPLETE                          CBSA_NAME  \
0                1             100.0  San Francisco-Oakland-Hayward, CA   
1                1             100.0  San Francisco-Oakland-Hayward, CA   
2                1             100.0  San Francisco-Oakland-Hayward, CA   
3                1             100.0  San Francisco-Oakland-Hayward, CA   
4                1             100.0  San Francisco-Oakland-Hayward, CA   

         COUNTY  SITE_LATITUDE  SITE_LONGITUDE  
0  Contra Costa      37.936013     -122.026154  
1  Contra Costa      37.936013     -122.026154  
2  Contra Costa      37.936013     -122.026154  
3  Contra Costa      37.936013     -122.026154  
4  Contra Costa      37.936013     -122.026154

In [44]:
#Check Count
PM10_2020.count()

Date                             244
Daily Mean PM10 Concentration    244
UNITS                            244
DAILY_AQI_VALUE                  244
DAILY_OBS_COUNT                  244
PERCENT_COMPLETE                 244
CBSA_NAME                        244
COUNTY                           244
SITE_LATITUDE                    244
SITE_LONGITUDE                   244
dtype: int64